name: bitchat_example
description: Example app demonstrating BitChat Flutter usage
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # BitChat Flutter package
  bitchat_flutter:
    path: ../
  
  # State management
  provider: ^6.1.2
  
  # UI components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
