name: bitchat_flutter
description: A Flutter package implementing BitChat protocol using Bluetooth Mesh Networks for decentralized peer-to-peer messaging
version: 1.0.0
homepage: https://github.com/buchion/bitchat_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Bluetooth and networking
  flutter_blue_plus: ^1.31.15
  permission_handler: ^11.3.1
  
  # State management
  provider: ^6.1.2
  
  # Crypto and security
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  
  # Utilities
  uuid: ^4.3.3
  logger: ^2.0.2+1
  
  # Platform channels for native functionality
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# flutter:
